export const posts: { name: string; text: string }[] = [
  {name: 'john_doe', text: 'Had a great time hiking this weekend!'},
  {name: 'jane_smith', text: 'Just finished reading a fantastic book.'},
  {name: 'cool_cat123', text: 'Love spending time with my family.'},
  {name: 'sunny_days', text: 'The weather is amazing today!'},
  {name: 'traveler89', text: 'Exploring new places is my passion.'},
  {name: 'foodie_heaven', text: 'Just tried the best pizza in town!'},
  {name: 'tech_guru', text: 'Excited about the latest tech trends.'},
  {name: 'fit_freak', text: 'Just completed a 5k run, feeling great!'},
  {name: 'bookworm_beth', text: 'Reading a fascinating mystery novel.'},
  {name: 'music_lover', text: 'Listening to my favorite band on repeat.'},
  {name: 'nature_enthusiast', text: 'Captured some stunning photos of the forest.'},
  {name: 'pet_pal', text: 'My dog just learned a new trick!'},
  {name: 'art_addict', text: 'Creating art is the best therapy.'},
  {name: 'fashionista', text: 'Loving the new fashion trends this season.'},
  {name: 'movie_buff', text: 'Just watched an amazing film last night.'},
  {name: 'chef_in_training', text: 'Cooked a delicious meal from scratch!'},
  {name: 'adventure_seeker', text: 'Planning my next big adventure.'},
  {name: 'health_nut', text: 'Smoothies are the best way to start the day.'},
  {name: 'history_buff', text: 'Visited a historic site today, so much to learn.'},
  {name: 'gaming_nerd', text: 'New video game release, can’t wait to play!'},
  {name: 'travel_junkie', text: 'Counting down the days to my next trip.'},
  {name: 'sports_fanatic', text: 'Watching the big game with friends.'},
  {name: 'yoga_lover', text: 'Yoga helps me stay balanced and calm.'},
  {name: 'baking_queen', text: 'Baked some delicious cookies today.'},
  {name: 'green_thumb', text: 'My garden is flourishing this season.'},
  {name: 'car_enthusiast', text: 'Just restored my classic car, looks brand new!'},
  {name: 'photography_fan', text: 'Captured a beautiful sunset this evening.'},
  {name: 'science_geek', text: 'Just read an interesting article on quantum physics.'},
  {name: 'workout_warrior', text: 'Hit a new personal best at the gym today.'},
  {name: 'happy_camper', text: 'Camping under the stars is the best experience.'}
];