export const posts: { name: string; text: string; tag: string }[] = [
  { name: 'john_doe', text: 'Had a great time hiking this weekend!', tag: 'hiking' },
  { name: 'jane_smith', text: 'Just finished reading a fantastic book.', tag: 'reading' },
  { name: 'cool_cat123', text: 'Love spending time with my family.', tag: 'family' },
  { name: 'sunny_days', text: 'The weather is amazing today!', tag: 'weather' },
  { name: 'traveler89', text: 'Exploring new places is my passion.', tag: 'travel' },
  { name: 'foodie_heaven', text: 'Just tried the best pizza in town!', tag: 'food' },
  { name: 'tech_guru', text: 'Excited about the latest tech trends.', tag: 'technology' },
  { name: 'fit_freak', text: 'Just completed a 5k run, feeling great!', tag: 'fitness' },
  { name: 'bookworm_beth', text: 'Reading a fascinating mystery novel.', tag: 'reading' },
  { name: 'music_lover', text: 'Listening to my favorite band on repeat.', tag: 'music' },
  { name: 'nature_enthusiast', text: 'Captured some stunning photos of the forest.', tag: 'nature' },
  { name: 'pet_pal', text: 'My dog just learned a new trick!', tag: 'pets' },
  { name: 'art_addict', text: 'Creating art is the best therapy.', tag: 'art' },
  { name: 'fashionista', text: 'Loving the new fashion trends this season.', tag: 'fashion' },
  { name: 'movie_buff', text: 'Just watched an amazing film last night.', tag: 'movies' },
  { name: 'chef_in_training', text: 'Cooked a delicious meal from scratch!', tag: 'cooking' },
  { name: 'adventure_seeker', text: 'Planning my next big adventure.', tag: 'adventure' },
  { name: 'health_nut', text: 'Smoothies are the best way to start the day.', tag: 'health' },
  { name: 'history_buff', text: 'Visited a historic site today, so much to learn.', tag: 'history' },
  { name: 'gaming_nerd', text: 'New video game release, can’t wait to play!', tag: 'gaming' },
  { name: 'travel_junkie', text: 'Counting down the days to my next trip.', tag: 'travel' },
  { name: 'sports_fanatic', text: 'Watching the big game with friends.', tag: 'sports' },
  { name: 'yoga_lover', text: 'Yoga helps me stay balanced and calm.', tag: 'yoga' },
  { name: 'baking_queen', text: 'Baked some delicious cookies today.', tag: 'baking' },
  { name: 'green_thumb', text: 'My garden is flourishing this season.', tag: 'gardening' },
  { name: 'car_enthusiast', text: 'Just restored my classic car, looks brand new!', tag: 'cars' },
  { name: 'photography_fan', text: 'Captured a beautiful sunset this evening.', tag: 'photography' },
  { name: 'science_geek', text: 'Just read an interesting article on quantum physics.', tag: 'science' },
  { name: 'workout_warrior', text: 'Hit a new personal best at the gym today.', tag: 'workout' },
  { name: 'happy_camper', text: 'Camping under the stars is the best experience.', tag: 'camping' }
];